### ISSUE TITLE
Space character in sh

### ISSUE THREAD

**Issue by sirjofri** [bhgv/Inferno-OS_Android#1]
When typing a space into a shell or a space is printed in the shell, the space is too small to be visible.

**How to reproduce:** Menu -> Shell -> type `ns` for example. Hit spacebar a few times an you can see the cursor pixel by pixel.

**Version:** current release v1.0b-0.4

_Thank you for your work! Great having Inferno on Android_

**Comment by bhgv** [comment]
checked. try a new one ( >= v1.0b-0.6 ). 
and write abou results

**Comment by sirjofri** [comment]
Works here. Thank you very much!
