### ISSUE TITLE
build errors on Linux

### ISSUE THREAD

**Issue by raingloom** [bhgv/Inferno-OS_Android#3]
```
(cd utils/ndate; mk  install)
arm-linux-androideabi-gcc -c -O -g -fPIE -fPIC -std=c99 -Wuninitialized -Wunused-variable -Wreturn-type -Wimplicit -Wattributes -I/home/rain/coding/Inferno-OS_Android/inferno-os/ndk_toolchain/sysroot/usr/include -I/home/rain/coding/Inferno-OS_Android/inferno-os/ndk_toolchain/sysroot/usr/include/arm-linux-androideabi -I/home/rain/coding/Inferno-OS_Android/inferno-os/ndk_toolchain/lib/gcc/arm-linux-androideabi/4.9.x/include -I/home/rain/coding/Inferno-OS_Android/inferno-os/Android/arm/include -I/home/rain/coding/Inferno-OS_Android/inferno-os/include -DLINUX_ARM -D__arm__ -D__ANDROID_API__=17 -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -marm -Wa,--noexecstack -Wformat -Werror=format-security -std=c99 --sysroot=/home/rain/coding/Inferno-OS_Android/inferno-os/ndk_toolchain/sysroot -o ndate.o ndate.c
ndate.c: In function 'main':
ndate.c:8:2: warning: implicit declaration of function 'time' [-Wimplicit-function-declaration]
  t = time(0);
  ^
arm-linux-androideabi-gcc -L/home/rain/coding/Inferno-OS_Android/inferno-os/ndk_toolchain/sysroot/usr/lib -llog -o o.out ndate.o /home/rain/coding/Inferno-OS_Android/inferno-os/Android/arm/lib/lib9.a 
rm -f /home/rain/coding/Inferno-OS_Android/inferno-os/Android/arm/bin/ndate && cp o.out /home/rain/coding/Inferno-OS_Android/inferno-os/Android/arm/bin/ndate
(cd emu; mk  install)
(cd Android; mk  install)
sh: line 1: ndate: command not found
arm-linux-androideabi-gcc -c -march=armv7-a -marm asm-arm.S
mk: no recipe to make 'devaudio_andr.o'
mk: echo "(cd $SYSTARG; ...  : exit status=exit(1)
mk: for j in ...  : exit status=exit(1)
```

system is Arch Linux

edit: i fixed the previous problem (it was a config error on my end) but now everything seems to be in order and it still refuses to build

**Comment by bhgv** [comment]
> ... cp o.out /home/rain/coding/Inferno-OS_Android/inferno-os/Android/**arm**/bin/ndate

make first inferno for linux-i386 platform. or you build this on linux-arm?
build process requires some internal tools (for example ndate). because, first it should be builten not for android-arm, but for your linux/windows/mac-<your processor>

if you don't want to build to android, build it from other repo better:

https://github.com/bhgv/Inferno-OS-bhgv

it is newer, contains scripts to build from linux and pair of changes. and you may replace inferno-os folder with last repo. all changes in the future will be based on this last repo.

**Comment by raingloom** [comment]
I was following the README.md, which didn't mention anything about that. The mkconfig file did, but I assumed the cross compilation has been taken care of.

If it's not a problem, I'll write an updated README with clearer instructions and send a PR.
